name: MetaTools
version: '1.0-SNAPSHOT'
main: org.BlazesMeta.metaTools.MetaTools
api-version: '1.21'
authors: [ Annhilati ]
website: https://github.com/Blazes-Meta
commands:
  test:
permissions:
  metatools.test:
    default: true